name: Deploy Debug

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

env:
  PUBLISH_PATH: "/app"

jobs:

  install-dotnet:
    runs-on: self-hosted
    environment: release
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
