name: Deploy Debug

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

env:
  PUBLISH_PATH: "/app"
  DOTNET_ROOT: "/lib/dotnet"
  DOTNET: ${{ env.DOTNET_ROOT }}/dotnet

jobs:

  deploy-web-app:
    runs-on: self-hosted
    environment: debug
    steps:
    - uses: actions/checkout@v4

    - name: Restore Dependencies
      run: ${{ env.DOTNET }} restore

    - name: Build
      run: ${{ env.DOTNET }} build Lux.DriverInterface.Server

    - name: Publish
      run: ${{ env.DOTNET }} publish Lux.DriverInterface.Server --no-build --configuration Debug --output ${{ env.PUBLISH_PATH }}

